export const match = (parameter) => {
    if (parameter.length === 0) {
        return undefined
    }
    const lowerParameter = parameter.toLowerCase();
    const exactMatch = data.find(
      element =>
        element.name.toLowerCase() === lowerParameter ||
        element.key.toLowerCase() === lowerParameter
    );
    if (exactMatch) {
      return exactMatch;
    }
    return data.find(
      element =>
        element.name.toLowerCase().includes(lowerParameter) ||
        element.key.toLowerCase().includes(lowerParameter)
    );
}

export const data = [
    { "key": "adonisjs", "name": "AdonisJS", "url": "https://docs.adonisjs.com/" },
    { "key": "akka", "name": "Akka", "url": "https://doc.akka.io/docs/akka/current/" },
    { "key": "alpinejs", "name": "Alpine.js", "url": "https://alpinejs.dev/start" },
    { "key": "anaconda", "name": "Anaconda", "url": "https://docs.anaconda.com/anaconda/" },
    { "key": "androidstudio", "name": "Android Studio", "url": "https://developer.android.com/studio" },
    { "key": "angular", "name": "Angular", "url": "https://angular.io/docs" },
    { "key": "angularjs", "name": "AngularJS", "url": "https://docs.angularjs.org/guide" },
    { "key": "angularmaterial", "name": "Angular Material", "url": "https://material.angular.io/" },
    { "key": "ansible", "name": "Ansible", "url": "https://docs.ansible.com/" },
    { "key": "antdesign", "name": "Ant Design", "url": "https://ant.design/docs/react/introduce" },
    { "key": "apache", "name": "Apache HTTP Server", "url": "https://httpd.apache.org/docs/" },
    { "key": "apacheairflow", "name": "Apache Airflow", "url": "https://airflow.apache.org/docs/apache-airflow/stable/" },
    { "key": "apachekafka", "name": "Apache Kafka", "url": "https://kafka.apache.org/documentation/" },
    { "key": "apachespark", "name": "Apache Spark", "url": "https://spark.apache.org/docs/latest/" },
    { "key": "apl", "name": "APL", "url": "https://aplwiki.com/" },
    { "key": "appcelerator", "name": "Appcelerator Titanium", "url": "https://docs.appcelerator.com/platform/latest/" },
    { "key": "appwrite", "name": "Appwrite", "url": "https://appwrite.io/docs" },
    { "key": "arduino", "name": "Arduino", "url": "https://www.arduino.cc/reference/en/" },
    { "key": "argocd", "name": "Argo CD", "url": "https://argo-cd.readthedocs.io/en/stable/" },
    { "key": "astro", "name": "Astro", "url": "https://docs.astro.build/" },
    { "key": "atom", "name": "Atom", "url": "https://flight-manual.atom.io/" },
    { "key": "azuredevops", "name": "Azure DevOps", "url": "https://docs.microsoft.com/en-us/azure/devops/?view=azure-devops" },
    { "key": "babel", "name": "Babel", "url": "https://babeljs.io/docs/en/" },
    { "key": "backbonejs", "name": "Backbone.js", "url": "https://backbonejs.org/" },
    { "key": "ballerina", "name": "Ballerina", "url": "https://ballerina.io/learn/" },
    { "key": "bamboo", "name": "Bamboo", "url": "https://confluence.atlassian.com/bamboo" },
    { "key": "bash", "name": "Bash", "url": "https://www.gnu.org/software/bash/manual/bash.html" },
    { "key": "beats", "name": "Elastic Beats", "url": "https://www.elastic.co/guide/en/beats/libbeat/current/index.html" },
    { "key": "bitbucket", "name": "Bitbucket", "url": "https://support.atlassian.com/bitbucket-cloud/docs/" },
    { "key": "blazor", "name": "Blazor", "url": "https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0" },
    { "key": "bootstrap", "name": "Bootstrap", "url": "https://getbootstrap.com/docs/5.0/getting-started/introduction/" },
    { "key": "bower", "name": "Bower", "url": "http://bower.io/docs/" },
    { "key": "browserstack", "name": "BrowserStack", "url": "https://www.browserstack.com/docs" },
    { "key": "bun", "name": "Bun", "url": "https://bun.sh/docs" },
    { "key": "c", "name": "C", "url": "https://devdocs.io/c/" },
    { "key": "cairo", "name": "Cairo", "url": "https://www.cairographics.org/documentation/" },
    { "key": "cakephp", "name": "CakePHP", "url": "https://book.cakephp.org/4/en/index.html" },
    { "key": "capacitor", "name": "Capacitor", "url": "https://capacitorjs.com/docs" },
    { "key": "carbon", "name": "Carbon Design System", "url": "https://www.carbondesignsystem.com/developing" },
    { "key": "ceylon", "name": "Ceylon", "url": "https://ceylon-lang.org/documentation/" },
    { "key": "clarity", "name": "Clarity Design System", "url": "https://clarity.design/documentation" },
    { "key": "clion", "name": "CLion", "url": "https://www.jetbrains.com/clion/documentation/" },
    { "key": "clojure", "name": "Clojure", "url": "https://clojure.org/guides/getting_started" },
    { "key": "clojurescript", "name": "ClojureScript", "url": "https://clojurescript.org/guides/quick-start" },
    { "key": "cloudflareworkers", "name": "Cloudflare Workers", "url": "https://developers.cloudflare.com/workers/" },
    { "key": "cmake", "name": "CMake", "url": "https://cmake.org/cmake/help/latest/" },
    { "key": "codepen", "name": "CodePen", "url": "https://blog.codepen.io/documentation/" },
    { "key": "coffeescript", "name": "CoffeeScript", "url": "https://coffeescript.org/" },
    { "key": "composer", "name": "Composer", "url": "https://getcomposer.org/doc/" },
    { "key": "consul", "name": "Consul", "url": "https://www.consul.io/docs" },
    { "key": "corejs", "name": "Core-js", "url": "https://github.com/zloirock/core-js#readme" },
    { "key": "cplusplus", "name": "C++", "url": "https://en.cppreference.com/w/cpp" },
    { "key": "crystal", "name": "Crystal", "url": "https://crystal-lang.org/reference/" },
    { "key": "csharp", "name": "C#", "url": "https://docs.microsoft.com/en-us/dotnet/csharp/" },
    { "key": "cypressio", "name": "Cypress", "url": "https://docs.cypress.io/" },
    { "key": "d3js", "name": "D3.js", "url": "https://github.com/d3/d3/wiki" },
    { "key": "dart", "name": "Dart", "url": "https://dart.dev/guides" },
    { "key": "datagrip", "name": "DataGrip", "url": "https://www.jetbrains.com/datagrip/documentation/" },
    { "key": "dataspell", "name": "DataSpell", "url": "https://www.jetbrains.com/dataspell/documentation/" },
    { "key": "dbeaver", "name": "DBeaver", "url": "https://dbeaver.io/documentation/" },
    { "key": "denojs", "name": "Deno", "url": "https://deno.land/manual" },
    { "key": "discordjs", "name": "Discord.js", "url": "https://discord.js.org/#/docs/main/stable/general/welcome" },
    { "key": "djangorest", "name": "Django REST framework", "url": "https://www.django-rest-framework.org/tutorial/quickstart/" },
    { "key": "docker", "name": "Docker", "url": "https://docs.docker.com/" },
    { "key": "doctrine", "name": "Doctrine ORM", "url": "https://www.doctrine-project.org/projects/doctrine-orm/en/latest/" },
    { "key": "dot-net", "name": ".NET", "url": "https://docs.microsoft.com/en-us/dotnet/" },
    { "key": "dotnetcore", "name": ".NET Core", "url": "https://docs.microsoft.com/en-us/dotnet/core/" },
    { "key": "dreamweaver", "name": "Adobe Dreamweaver", "url": "https://helpx.adobe.com/dreamweaver/tutorials.html" },
    { "key": "dropwizard", "name": "Dropwizard", "url": "https://www.dropwizard.io/en/latest/" },
    { "key": "drupal", "name": "Drupal", "url": "https://www.drupal.org/docs" },
    { "key": "eclipse", "name": "Eclipse", "url": "https://www.eclipse.org/documentation/" },
    { "key": "ecto", "name": "Ecto", "url": "https://hexdocs.pm/ecto/" },
    { "key": "electron", "name": "Electron", "url": "https://www.electronjs.org/docs" },
    { "key": "eleventy", "name": "Eleventy", "url": "https://www.11ty.dev/docs/" },
    { "key": "elixir", "name": "Elixir", "url": "https://elixir-lang.org/docs.html" },
    { "key": "elm", "name": "Elm", "url": "https://guide.elm-lang.org/" },
    { "key": "emacs", "name": "GNU Emacs", "url": "https://www.gnu.org/software/emacs/manual/" },
    { "key": "embeddedc", "name": "Embedded C", "url": "https://en.wikipedia.org/wiki/Embedded_C" },
    { "key": "ember", "name": "Ember.js", "url": "https://emberjs.com/api/" },
    { "key": "envoy", "name": "Envoy", "url": "https://www.envoyproxy.io/docs" },
    { "key": "erlang", "name": "Erlang", "url": "https://erlang.org/doc/" },
    { "key": "eslint", "name": "ESLint", "url": "https://eslint.org/docs/latest/" },
    { "key": "express", "name": "Express", "url": "https://expressjs.com/en/starter/installing.html" },
    { "key": "fastapi", "name": "FastAPI", "url": "https://fastapi.tiangolo.com/" },
    { "key": "fastify", "name": "Fastify", "url": "https://www.fastify.io/docs/latest/" },
    { "key": "feathersjs", "name": "FeathersJS", "url": "https://docs.feathersjs.com/" },
    { "key": "filezilla", "name": "FileZilla", "url": "https://wiki.filezilla-project.org/Documentation" },
    { "key": "firebase", "name": "Firebase", "url": "https://firebase.google.com/docs" },
    { "key": "flask", "name": "Flask", "url": "https://flask.palletsprojects.com/en/latest/" },
    { "key": "flutter", "name": "Flutter", "url": "https://flutter.dev/docs" },
    { "key": "fortran", "name": "Fortran", "url": "https://www.fortran90.org/" },
    { "key": "foundation", "name": "Foundation", "url": "https://get.foundation/sites/docs/" },
    { "key": "framermotion", "name": "Framer Motion", "url": "https://www.framer.com/docs/motion/" },
    { "key": "framework7", "name": "Framework7", "url": "https://framework7.io/docs/" },
    { "key": "fsharp", "name": "F#", "url": "https://fsharp.org/learn/" },
    { "key": "gatling", "name": "Gatling", "url": "https://gatling.io/docs/current/" },
    { "key": "gatsby", "name": "Gatsby", "url": "https://www.gatsbyjs.com/docs/" },
    { "key": "gazebo", "name": "Gazebo", "url": "http://gazebosim.org/tutorials" },
    { "key": "gcc", "name": "GCC", "url": "https://gcc.gnu.org/onlinedocs/" },
    { "key": "git", "name": "Git", "url": "https://git-scm.com/doc" },
    { "key": "gitbook", "name": "GitBook", "url": "https://docs.gitbook.com/" },
    { "key": "github", "name": "GitHub", "url": "https://docs.github.com/" },
    { "key": "githubactions", "name": "GitHub Actions", "url": "https://docs.github.com/en/actions" },
    { "key": "githubcodespaces", "name": "GitHub Codespaces", "url": "https://docs.github.com/en/codespaces" },
    { "key": "gitlab", "name": "GitLab", "url": "https://docs.gitlab.com/" },
    { "key": "gitpod", "name": "Gitpod", "url": "https://www.gitpod.io/docs/" },
    { "key": "go", "name": "Go", "url": "https://go.dev/doc/" },
    { "key": "godot", "name": "Godot", "url": "https://docs.godotengine.org/en/stable/" },
    { "key": "goland", "name": "GoLand", "url": "https://www.jetbrains.com/goland/documentation/" },
    { "key": "gradle", "name": "Gradle", "url": "https://docs.gradle.org/current/userguide/userguide.html" },
    { "key": "grafana", "name": "Grafana", "url": "https://grafana.com/docs/" },
    { "key": "grails", "name": "Grails", "url": "https://grails.org/documentation.html" },
    { "key": "groovy", "name": "Groovy", "url": "https://groovy-lang.org/documentation.html" },
    { "key": "grpc", "name": "gRPC", "url": "https://grpc.io/docs/" },
    { "key": "grunt", "name": "Grunt", "url": "https://gruntjs.com/getting-started" },
    { "key": "hadoop", "name": "Hadoop", "url": "https://hadoop.apache.org/docs/stable/" },
    { "key": "handlebars", "name": "Handlebars.js", "url": "https://handlebarsjs.com/guide/" },
    { "key": "hardhat", "name": "Hardhat", "url": "https://hardhat.org/getting-started/" },
    { "key": "haskell", "name": "Haskell", "url": "https://www.haskell.org/documentation/" },
    { "key": "haxe", "name": "Haxe", "url": "https://haxe.org/documentation/introduction/" },
    { "key": "helm", "name": "Helm", "url": "https://helm.sh/docs/" },
    { "key": "hibernate", "name": "Hibernate ORM", "url": "https://hibernate.org/orm/documentation/" },
    { "key": "homebrew", "name": "Homebrew", "url": "https://docs.brew.sh/" },
    { "key": "hugo", "name": "Hugo", "url": "https://gohugo.io/documentation/" },
    { "key": "insomnia", "name": "Insomnia", "url": "https://support.insomnia.rest/" },
    { "key": "intellij", "name": "IntelliJ IDEA", "url": "https://www.jetbrains.com/idea/documentation/" },
    { "key": "ionic", "name": "Ionic", "url": "https://ionicframework.com/docs" },
    { "key": "jaegertracing", "name": "Jaeger", "url": "https://www.jaegertracing.io/docs/" },
    { "key": "jasmine", "name": "Jasmine", "url": "https://jasmine.github.io/pages/getting_started.html" },
    { "key": "java", "name": "Java", "url": "https://docs.oracle.com/en/java/" },
    { "key": "javascript", "name": "JavaScript", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
    { "key": "jeet", "name": "Jeet", "url": "http://jeet.gs/" },
    { "key": "jekyll", "name": "Jekyll", "url": "https://jekyllrb.com/docs/" },
    { "key": "jenkins", "name": "Jenkins", "url": "https://www.jenkins.io/doc/" },
    { "key": "jetpackcompose", "name": "Jetpack Compose", "url": "https://developer.android.com/jetpack/compose/documentation" },
    { "key": "jira", "name": "Jira", "url": "https://support.atlassian.com/jira-software-cloud/" },
    { "key": "jiraalign", "name": "Jira Align", "url": "https://www.atlassian.com/software/jira/align" },
    { "key": "jquery", "name": "jQuery", "url": "https://api.jquery.com/" },
    { "key": "julia", "name": "Julia", "url": "https://docs.julialang.org/" },
    { "key": "junit", "name": "JUnit", "url": "https://junit.org/junit5/docs/current/user-guide/" },
    { "key": "jupyter", "name": "Jupyter", "url": "https://jupyter.org/documentation" },
    { "key": "k6", "name": "k6", "url": "https://k6.io/docs/" },
    { "key": "karatelabs", "name": "Karatelabs", "url": "https://karatelabs.io/docs/" },
    { "key": "karma", "name": "Karma", "url": "https://karma-runner.github.io/latest/index.html" },
    { "key": "keras", "name": "Keras", "url": "https://keras.io/api/" },
    { "key": "kibana", "name": "Kibana", "url": "https://www.elastic.co/guide/en/kibana/current/index.html" },
    { "key": "knexjs", "name": "Knex.js", "url": "https://knexjs.org/" },
    { "key": "kotlin", "name": "Kotlin", "url": "https://kotlinlang.org/docs/home.html" },
    { "key": "krakenjs", "name": "Kraken.js", "url": "https://www.npmjs.com/package/kraken-js" },
    { "key": "ktor", "name": "Ktor", "url": "https://ktor.io/docs/" },
    { "key": "kubernetes", "name": "Kubernetes", "url": "https://kubernetes.io/docs/home/" },
    { "key": "labview", "name": "LabVIEW", "url": "https://zone.ni.com/reference/en-XX/help/371361R-01/" },
    { "key": "laravel", "name": "Laravel", "url": "https://laravel.com/docs/" },
    { "key": "latex", "name": "LaTeX", "url": "https://www.latex-project.org/help/documentation/" },
    { "key": "liquibase", "name": "Liquibase", "url": "https://www.liquibase.org/documentation" },
    { "key": "livewire", "name": "Livewire", "url": "https://laravel-livewire.com/docs" },
    { "key": "llvm", "name": "LLVM", "url": "https://llvm.org/docs/" },
    { "key": "lodash", "name": "Lodash", "url": "https://lodash.com/docs/" },
    { "key": "logstash", "name": "Logstash", "url": "https://www.elastic.co/guide/en/logstash/current/index.html" },
    { "key": "lua", "name": "Lua", "url": "https://www.lua.org/manual/5.4/" },
    { "key": "lumen", "name": "Lumen", "url": "https://lumen.laravel.com/docs" },
    { "key": "materializecss", "name": "Materialize CSS", "url": "https://materializecss.com/getting-started.html" },
    { "key": "materialui", "name": "Material-UI", "url": "https://mui.com/material-ui/getting-started/overview/" },
    { "key": "matlab", "name": "MATLAB", "url": "https://www.mathworks.com/help/matlab/" },
    { "key": "matplotlib", "name": "Matplotlib", "url": "https://matplotlib.org/stable/contents.html" },
    { "key": "maven", "name": "Maven", "url": "https://maven.apache.org/guides/index.html" },
    { "key": "meteor", "name": "Meteor", "url": "https://docs.meteor.com/" },
    { "key": "mithril", "name": "Mithril.js", "url": "https://mithril.js.org/" },
    { "key": "mobx", "name": "MobX", "url": "https://mobx.js.org/README.html" },
    { "key": "mocha", "name": "Mocha", "url": "https://mochajs.org/" },
    { "key": "moleculer", "name": "Moleculer", "url": "https://moleculer.services/docs/0.14/" },
    { "key": "mongoose", "name": "Mongoose", "url": "https://mongoosejs.com/docs/" },
    { "key": "nano", "name": "Nano", "url": "https://nano-editor.org/dist/v5/nano.html" },
    { "key": "neovim", "name": "Neovim", "url": "https://neovim.io/doc/" },
    { "key": "nestjs", "name": "NestJS", "url": "https://docs.nestjs.com/" },
    { "key": "netlify", "name": "Netlify", "url": "https://docs.netlify.com/" },
    { "key": "networkx", "name": "NetworkX", "url": "https://networkx.org/documentation/stable/" },
    { "key": "nextjs", "name": "Next.js", "url": "https://nextjs.org/docs" },
    { "key": "nginx", "name": "NGINX", "url": "https://nginx.org/en/docs/" },
    { "key": "ngrx", "name": "NgRx", "url": "https://ngrx.io/docs" },
    { "key": "nhibernate", "name": "NHibernate", "url": "https://nhibernate.info/doc/nhibernate-reference/index.html" },
    { "key": "nim", "name": "Nim", "url": "https://nim-lang.org/docs.html" },
    { "key": "nimble", "name": "Nimble", "url": "https://github.com/nim-lang/nimble#readme" },
    { "key": "nixos", "name": "NixOS", "url": "https://nixos.org/manual/nixos/stable/" },
    { "key": "nodejs", "name": "Node.js", "url": "https://nodejs.org/en/docs/" },
    { "key": "nodemon", "name": "Nodemon", "url": "https://nodemon.io/" },
    { "key": "nodewebkit", "name": "NW.js", "url": "https://nwjs.io/docs/" },
    { "key": "nomad", "name": "Nomad", "url": "https://www.nomadproject.io/docs" },
    { "key": "nuget", "name": "NuGet", "url": "https://docs.microsoft.com/en-us/nuget/" },
    { "key": "numpy", "name": "NumPy", "url": "https://numpy.org/doc/" },
    { "key": "nuxtjs", "name": "Nuxt.js", "url": "https://nuxtjs.org/docs" },
    { "key": "ocaml", "name": "OCaml", "url": "https://ocaml.org/manual/" },
    { "key": "ohmyzsh", "name": "Oh My Zsh", "url": "https://ohmyz.sh/" },
    { "key": "openal", "name": "OpenAL", "url": "http://openal.org/documentation/" },
    { "key": "openapi", "name": "OpenAPI", "url": "https://swagger.io/specification/" },
    { "key": "opencl", "name": "OpenCL", "url": "https://www.khronos.org/registry/OpenCL/specs/" },
    { "key": "opencv", "name": "OpenCV", "url": "https://docs.opencv.org/" },
    { "key": "opengl", "name": "OpenGL", "url": "https://www.opengl.org/documentation/" },
    { "key": "opentelemetry", "name": "OpenTelemetry", "url": "https://opentelemetry.io/docs/" },
    { "key": "ory", "name": "ORY", "url": "https://www.ory.sh/docs/" },
    { "key": "p5js", "name": "p5.js", "url": "https://p5js.org/reference/" },
    { "key": "packer", "name": "Packer", "url": "https://www.packer.io/docs" },
    { "key": "pandas", "name": "Pandas", "url": "https://pandas.pydata.org/docs/" },
    { "key": "perl", "name": "Perl", "url": "https://perldoc.perl.org/" },
    { "key": "phalcon", "name": "Phalcon", "url": "https://docs.phalcon.io/" },
    { "key": "phoenix", "name": "Phoenix", "url": "https://hexdocs.pm/phoenix/overview.html" },
    { "key": "photonengine", "name": "Photon Engine", "url": "https://doc.photonengine.com/en-us/realtime/current/getting-started/photon-realtime-intro" },
    { "key": "php", "name": "PHP", "url": "https://www.php.net/docs.php" },
    { "key": "phpstorm", "name": "PhpStorm", "url": "https://www.jetbrains.com/phpstorm/documentation/" },
    { "key": "playwright", "name": "Playwright", "url": "https://playwright.dev/docs/intro" },
    { "key": "plotly", "name": "Plotly", "url": "https://plotly.com/python/" },
    { "key": "pnpm", "name": "pnpm", "url": "https://pnpm.io/motivation" },
    { "key": "podman", "name": "Podman", "url": "https://podman.io/getting-started/" },
    { "key": "poetry", "name": "Poetry", "url": "https://python-poetry.org/docs/" },
    { "key": "polygon", "name": "Polygon", "url": "https://polygon.io/docs/" },
    { "key": "portainer", "name": "Portainer", "url": "https://docs.portainer.io/" },
    { "key": "postcss", "name": "PostCSS", "url": "https://postcss.org/" },
    { "key": "postman", "name": "Postman", "url": "https://learning.postman.com/docs/getting-started/introduction/" },
    { "key": "powershell", "name": "PowerShell", "url": "https://docs.microsoft.com/en-us/powershell/" },
    { "key": "premierepro", "name": "Adobe Premiere Pro", "url": "https://helpx.adobe.com/premiere-pro/tutorials.html" },
    { "key": "prisma", "name": "Prisma", "url": "https://www.prisma.io/docs/" },
    { "key": "processing", "name": "Processing", "url": "https://processing.org/tutorials/" },
    { "key": "prolog", "name": "Prolog", "url": "https://www.swi-prolog.org/pldoc/doc_for?object=manual" },
    { "key": "prometheus", "name": "Prometheus", "url": "https://prometheus.io/docs/introduction/overview/" },
    { "key": "protractor", "name": "Protractor", "url": "https://www.protractortest.org/#/tutorial" },
    { "key": "pulsar", "name": "Apache Pulsar", "url": "https://pulsar.apache.org/docs/en/" },
    { "key": "pulumi", "name": "Pulumi", "url": "https://www.pulumi.com/docs/" },
    { "key": "puppeteer", "name": "Puppeteer", "url": "https://pptr.dev/" },
    { "key": "purescript", "name": "PureScript", "url": "https://www.purescript.org/documentation/" },
    { "key": "putty", "name": "PuTTY", "url": "https://the.earth.li/~sgtatham/putty/latest/htmldoc/" },
    { "key": "pycharm", "name": "PyCharm", "url": "https://www.jetbrains.com/pycharm/documentation/" },
    { "key": "pypi", "name": "PyPI", "url": "https://pypi.org/help/" },
    { "key": "pytest", "name": "pytest", "url": "https://docs.pytest.org/en/stable/" },
    { "key": "python", "name": "Python", "url": "https://docs.python.org/3/" },
    { "key": "pytorch", "name": "PyTorch", "url": "https://pytorch.org/docs/stable/index.html" },
    { "key": "qodana", "name": "Qodana", "url": "https://www.jetbrains.com/help/qodana/overview.html" },
    { "key": "qt", "name": "Qt", "url": "https://doc.qt.io/" },
    { "key": "quarkus", "name": "Quarkus", "url": "https://quarkus.io/guides/" },
    { "key": "quasar", "name": "Quasar Framework", "url": "https://quasar.dev/introduction-to-quasar" },
    { "key": "qwik", "name": "Qwik", "url": "https://qwik.builder.io/docs/" },
    { "key": "r", "name": "R", "url": "https://cran.r-project.org/manuals.html" },
    { "key": "rabbitmq", "name": "RabbitMQ", "url": "https://www.rabbitmq.com/documentation.html" },
    { "key": "railway", "name": "Railway", "url": "https://railway.app/docs" },
    { "key": "rancher", "name": "Rancher", "url": "https://rancher.com/docs/" },
    { "key": "react", "name": "React", "url": "https://reactjs.org/docs/getting-started.html" },
    { "key": "reactbootstrap", "name": "React Bootstrap", "url": "https://react-bootstrap.github.io/getting-started/introduction/" },
    { "key": "reactnavigation", "name": "React Navigation", "url": "https://reactnavigation.org/docs/getting-started" },
    { "key": "reactrouter", "name": "React Router", "url": "https://reactrouter.com/en/main" },
    { "key": "readthedocs", "name": "Read the Docs", "url": "https://docs.readthedocs.io/en/stable/" },
    { "key": "redux", "name": "Redux", "url": "https://redux.js.org/introduction/getting-started" },
    { "key": "renpy", "name": "Ren'Py", "url": "https://www.renpy.org/doc/html/" },
    { "key": "replit", "name": "Replit", "url": "https://docs.replit.com/" },
    { "key": "rider", "name": "Rider", "url": "https://www.jetbrains.com/rider/documentation/" },
    { "key": "rocksdb", "name": "RocksDB", "url": "https://github.com/facebook/rocksdb/blob/main/README.md" },
    { "key": "rollup", "name": "Rollup", "url": "https://rollupjs.org/guide/en/" },
    { "key": "ros", "name": "ROS", "url": "https://docs.ros.org/" },
    { "key": "rspec", "name": "RSpec", "url": "https://rspec.info/documentation/" },
    { "key": "rstudio", "name": "RStudio", "url": "https://support.rstudio.com/hc/en-us/articles/200711843-Documentation" },
    { "key": "ruby", "name": "Ruby", "url": "https://www.ruby-lang.org/en/documentation/" },
    { "key": "rubymine", "name": "RubyMine", "url": "https://www.jetbrains.com/rubymine/documentation/" },
    { "key": "rust", "name": "Rust", "url": "https://doc.rust-lang.org/" },
    { "key": "rxjs", "name": "RxJS", "url": "https://rxjs.dev/guide/overview" },
    { "key": "sass", "name": "Sass", "url": "https://sass-lang.com/documentation" },
    { "key": "scala", "name": "Scala", "url": "https://docs.scala-lang.org/" },
    { "key": "scikitlearn", "name": "scikit-learn", "url": "https://scikit-learn.org/stable/documentation.html" },
    { "key": "sdl", "name": "SDL", "url": "https://wiki.libsdl.org/FrontPage" },
    { "key": "selenium", "name": "Selenium", "url": "https://www.selenium.dev/documentation/" },
    { "key": "sema", "name": "Sema", "url": "https://sema.run/docs" },
    { "key": "sentry", "name": "Sentry", "url": "https://docs.sentry.io/" },
    { "key": "sequelize", "name": "Sequelize", "url": "https://sequelize.org/master/manual/" },
    { "key": "shopware", "name": "Shopware", "url": "https://docs.shopware.com/en/shopware-platform-dev-en" },
    { "key": "shotgrid", "name": "ShotGrid", "url": "https://developer.shotgridsoftware.com/" },
    { "key": "sketch", "name": "Sketch", "url": "https://developer.sketch.com/" },
    { "key": "slack", "name": "Slack", "url": "https://api.slack.com/" },
    { "key": "socketio", "name": "Socket.IO", "url": "https://socket.io/docs/v4" },
    { "key": "solidity", "name": "Solidity", "url": "https://docs.soliditylang.org/en/v0.8.17/" },
    { "key": "solidjs", "name": "SolidJS", "url": "https://solidjs.com/docs/latest" },
    { "key": "sonarqube", "name": "SonarQube", "url": "https://docs.sonarqube.org/latest/" },
    { "key": "sourcetree", "name": "Sourcetree", "url": "https://confluence.atlassian.com/get-started-with-sourcetree" },
    { "key": "spack", "name": "Spack", "url": "https://spack.readthedocs.io/en/latest/" },
    { "key": "spring", "name": "Spring Framework", "url": "https://spring.io/projects/spring-framework" },
    { "key": "spss", "name": "IBM SPSS", "url": "https://www.ibm.com/analytics/spss-statistics-software" },
    { "key": "spyder", "name": "Spyder", "url": "https://docs.spyder-ide.org/" },
    { "key": "sqlalchemy", "name": "SQLAlchemy", "url": "https://docs.sqlalchemy.org/en/14/" },
    { "key": "sqldeveloper", "name": "SQL Developer", "url": "https://www.oracle.com/database/technologies/appdev/sqldeveloper.html" },
    { "key": "sqlite", "name": "SQLite", "url": "https://sqlite.org/docs.html" },
    { "key": "ssh", "name": "SSH", "url": "https://www.openssh.com/manual.html" },
    { "key": "stackoverflow", "name": "Stack Overflow", "url": "https://stackoverflow.com/help" },
    { "key": "storybook", "name": "Storybook", "url": "https://storybook.js.org/docs" },
    { "key": "streamlit", "name": "Streamlit", "url": "https://docs.streamlit.io/" },
    { "key": "stylus", "name": "Stylus", "url": "https://stylus-lang.com/docs.html" },
    { "key": "subversion", "name": "Subversion", "url": "https://subversion.apache.org/docs/" },
    { "key": "supabase", "name": "Supabase", "url": "https://supabase.com/docs" },
    { "key": "svelte", "name": "Svelte", "url": "https://svelte.dev/docs" },
    { "key": "swagger", "name": "Swagger", "url": "https://swagger.io/docs/" },
    { "key": "swift", "name": "Swift", "url": "https://swift.org/documentation/" },
    { "key": "swiper", "name": "Swiper", "url": "https://swiperjs.com/get-started" },
    { "key": "symfony", "name": "Symfony", "url": "https://symfony.com/doc/current/index.html" },
    { "key": "tailwindcss", "name": "Tailwind CSS", "url": "https://tailwindcss.com/docs" },
    { "key": "tauri", "name": "Tauri", "url": "https://tauri.app/v1/guides/" },
    { "key": "tensorflow", "name": "TensorFlow", "url": "https://www.tensorflow.org/guide" },
    { "key": "terraform", "name": "Terraform", "url": "https://www.terraform.io/docs" },
    { "key": "tex", "name": "TeX", "url": "https://www.latex-project.org/help/documentation/" },
    { "key": "thealgorithms", "name": "The Algorithms", "url": "https://thealgorithms.com/" },
    { "key": "threedsmax", "name": "3DS Max", "url": "https://knowledge.autodesk.com/support/3ds-max" },
    { "key": "threejs", "name": "Three.js", "url": "https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene" },
    { "key": "titaniumsdk", "name": "Titanium SDK", "url": "https://titaniumsdk.com/guide/Titanium_SDK_Home.html" },
    { "key": "tomcat", "name": "Apache Tomcat", "url": "https://tomcat.apache.org/tomcat-9.0-doc/index.html" },
    { "key": "tortoisegit", "name": "TortoiseGit", "url": "https://tortoisegit.org/documentation/" },
    { "key": "towergit", "name": "Tower", "url": "https://www.git-tower.com/learn/" },
    { "key": "traefikmesh", "name": "Traefik Mesh", "url": "https://doc.traefik.io/traefik-mesh/" },
    { "key": "traefikproxy", "name": "Traefik Proxy", "url": "https://doc.traefik.io/traefik/" },
    { "key": "travis", "name": "Travis CI", "url": "https://docs.travis-ci.com/" },
    { "key": "trpc", "name": "tRPC", "url": "https://trpc.io/docs" },
    { "key": "typescript", "name": "TypeScript", "url": "https://www.typescriptlang.org/docs/" },
    { "key": "unifiedmodelinglanguage", "name": "Unified Modeling Language (UML)", "url": "https://www.uml.org/" },
    { "key": "unity", "name": "Unity", "url": "https://docs.unity3d.com/" },
    { "key": "unrealengine", "name": "Unreal Engine", "url": "https://docs.unrealengine.com/" },
    { "key": "uwsgi", "name": "uWSGI", "url": "https://uwsgi-docs.readthedocs.io/en/latest/" },
    { "key": "v8", "name": "V8", "url": "https://v8.dev/docs" },
    { "key": "vagrant", "name": "Vagrant", "url": "https://www.vagrantup.com/docs" },
    { "key": "vala", "name": "Vala", "url": "https://valadoc.org/" },
    { "key": "vault", "name": "Vault", "url": "https://www.vaultproject.io/docs" },
    { "key": "vercel", "name": "Vercel", "url": "https://vercel.com/docs" },
    { "key": "vertx", "name": "Vert.x", "url": "https://vertx.io/docs/" },
    { "key": "vim", "name": "Vim", "url": "https://vimhelp.org/" },
    { "key": "visualbasic", "name": "Visual Basic", "url": "https://docs.microsoft.com/en-us/visualstudio/vb-developers/" },
    { "key": "visualstudio", "name": "Visual Studio", "url": "https://docs.microsoft.com/en-us/visualstudio/" },
    { "key": "vite", "name": "Vite", "url": "https://vitejs.dev/guide/" },
    { "key": "vitejs", "name": "Vite.js", "url": "https://vitejs.dev/guide/" },
    { "key": "vitess", "name": "Vitess", "url": "https://vitess.io/docs/" },
    { "key": "vitest", "name": "Vitest", "url": "https://vitest.dev/guide/" },
    { "key": "vscode", "name": "Visual Studio Code", "url": "https://code.visualstudio.com/docs" },
    { "key": "vsphere", "name": "vSphere", "url": "https://docs.vmware.com/en/VMware-vSphere/index.html" },
    { "key": "vuejs", "name": "Vue.js", "url": "https://vuejs.org/guide/introduction.html" },
    { "key": "vuestorefront", "name": "Vue Storefront", "url": "https://docs.vuestorefront.io/" },
    { "key": "vuetify", "name": "Vuetify", "url": "https://vuetifyjs.com/en/getting-started/installation/" },
    { "key": "vyper", "name": "Vyper", "url": "https://vyper.readthedocs.io/en/stable/" },
    { "key": "wasm", "name": "WebAssembly", "url": "https://webassembly.org/docs/" },
    { "key": "weblate", "name": "Weblate", "url": "https://docs.weblate.org/en/latest/" },
    { "key": "webpack", "name": "Webpack", "url": "https://webpack.js.org/concepts/" },
    { "key": "webstorm", "name": "WebStorm", "url": "https://www.jetbrains.com/webstorm/documentation/" },
    { "key": "xamarin", "name": "Xamarin", "url": "https://docs.microsoft.com/en-us/xamarin/" },
    { "key": "xcode", "name": "Xcode", "url": "https://developer.apple.com/xcode/" },
    { "key": "yarn", "name": "Yarn", "url": "https://classic.yarnpkg.com/en/docs" },
    { "key": "yii", "name": "Yii", "url": "https://www.yiiframework.com/doc/guide/2.0/en" },
    { "key": "zend", "name": "Zend Framework", "url": "https://docs.laminas.dev/" },
    { "key": "zig", "name": "Zig", "url": "https://ziglang.org/documentation/master/" }
]  
  